name: frosthub
description: A new Flutter project.

publish_to: 'none' # Remove this line if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  uuid: ^4.2.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  flutter_speed_dial: ^7.0.0
  share_plus: ^7.2.1
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
