// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWW43fke6RF5GTzTVzrfQWKi-LMw_aEPs',
    appId: '1:410532748747:web:c4052b8a682f2967cf6a4e',
    messagingSenderId: '410532748747',
    projectId: 'frosthub-6ca1c',
    authDomain: 'frosthub-6ca1c.firebaseapp.com',
    storageBucket: 'frosthub-6ca1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJAMlH_-6FpNesSMzBKNIIsJ-vXJst3w',
    appId: '1:410532748747:android:f9c89e468d0aab54cf6a4e',
    messagingSenderId: '410532748747',
    projectId: 'frosthub-6ca1c',
    storageBucket: 'frosthub-6ca1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClpMzacRDkUuZnyiVwVm7sbeUpchVckGQ',
    appId: '1:410532748747:ios:a141cd2280446d24cf6a4e',
    messagingSenderId: '410532748747',
    projectId: 'frosthub-6ca1c',
    storageBucket: 'frosthub-6ca1c.firebasestorage.app',
    androidClientId: '410532748747-2dhgk5ckf6gc40soujsqr77ga9k8pj4f.apps.googleusercontent.com',
    iosClientId: '410532748747-1skso3t41f7feji2fg21f5meqlfkp6aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.frosthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClpMzacRDkUuZnyiVwVm7sbeUpchVckGQ',
    appId: '1:410532748747:ios:a141cd2280446d24cf6a4e',
    messagingSenderId: '410532748747',
    projectId: 'frosthub-6ca1c',
    storageBucket: 'frosthub-6ca1c.firebasestorage.app',
    androidClientId: '410532748747-2dhgk5ckf6gc40soujsqr77ga9k8pj4f.apps.googleusercontent.com',
    iosClientId: '410532748747-1skso3t41f7feji2fg21f5meqlfkp6aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.frosthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWW43fke6RF5GTzTVzrfQWKi-LMw_aEPs',
    appId: '1:410532748747:web:abfef17881fd0b2bcf6a4e',
    messagingSenderId: '410532748747',
    projectId: 'frosthub-6ca1c',
    authDomain: 'frosthub-6ca1c.firebaseapp.com',
    storageBucket: 'frosthub-6ca1c.firebasestorage.app',
  );

}